# Generated by Django 3.2.9 on 2022-02-27 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150, verbose_name='title')),
                ('release_date', models.IntegerField(default=None, verbose_name='year')),
                ('genre', models.CharField(default=None, max_length=200, verbose_name='genre')),
                ('duration', models.IntegerField(default=None, verbose_name='duration')),
                ('country', models.CharField(default=None, max_length=50, verbose_name='country')),
                ('director', models.CharField(default=None, max_length=70, verbose_name='director')),
                ('actors', models.CharField(default=None, max_length=1000, verbose_name='actors')),
                ('score', models.DecimalField(decimal_places=3, default=None, max_digits=4, verbose_name='avg_vote')),
                ('votes', models.IntegerField(default=None, verbose_name='votes')),
                ('poster', models.URLField(default=None, max_length=2000, verbose_name='poster')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('rating', models.IntegerField()),
                ('add_t', models.DateTimeField(auto_now_add=True)),
                ('edit_t', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
