# Generated by Django 3.2.9 on 2022-03-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(default=None, max_length=250, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(default=None, max_length=250, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='score',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, verbose_name='avg_vote'),
        ),
    ]
